
builds:
  - binary: gosandbox
    id: gosandbox
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    main: ./scripts/interactive

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: gosandbox
    homepage: "https://github.com/josephedward/gosandbox"
    tap:
      owner: josephedward
      name: homebrew  
    commit_author:
      name: josephedward
      email: josephedwardwork@gmail.com

checksum:
  name_template: 'checksums.txt'