version: "3"

tasks:
  get-aws-creds:
    cmds:
      - echo "Task - testing provider"
      - go clean -modcache
      - go test ./test/provider_test.go -v
  run-cli:
    cmds:
      - echo "Task - testing interactive CLI"
      - go clean -testcache
      - go run ./scripts/interactive.go -v -rod="show,slow=1s,trace"
  test-all:
    cmds:
      - echo "Task - testing all methods"
      - go clean -modcache
      - cd /test
      - go test -v
  get-creds-visible:
    cmds:
      - echo "Task - testing provider with visible browser"
      - go clean -modcache
      - go test ./test/provider_test.go -v -rod="show,slow=1s,trace"