version: "3"

tasks:
  test-methods:
    cmds:
      - echo "Task test-env"
      - go clean -modcache
      - go test ./test/methods_test.go -v 
  test-methods-slow:
    cmds:
      - echo "Task test-env-slow"
      - go clean -modcache
      - go test ./test/methods_test.go -v -rod="show,slow=1s,trace"   
  test-provider:
    cmds:
      - echo "Task test-env"
      - go clean -modcache
      - go test ./test/provider_test.go -v 
  test-provider-slow:
    cmds:
      - echo "Task test-env-slow"
      - go clean -modcache
      - go test ./test/provider_test.go -v -rod="show,slow=1s,trace"   
  test-interactive:
    cmds:
      - echo "Task test-interactive"
      - go clean -testcache
      - go test ./test/interactive_test.go -v
  test-interactive-slow:
    cmds:
      - echo "Task test-interactive-slow"
      - go clean -testcache
      - go test ./test/interactive_test.go -v -rod="show,slow=1s,trace"   